const RACCORDEMENT_RESEAU = [
    {
      id: 1,
      code: "S6902019",
      name: "Coffret ECP 3D",
      quantity: 0,
      unite: "U",
    },
    { id: 2, code: "S6902033", name: "Borne ECP 3D", quantity: 0, unite: "U" },
    {
      id: 3,
      code: "S6902054",
      name: "Coffret ECP 2D",
      quantity: 0,
      unite: "U",
    },
    { id: 4, code: "S6902053", name: "B ECP 2D", quantity: 0, unite: "U" },
    {
      id: 5,
      code: "S6902035",
      name: "Kit passage de 2D en 3D",
      quantity: 0,
      unite: "U",
    },
    {
      id: 6,
      code: "S6798304",
      name: "Extrémité rétractable BT E4R 240",
      quantity: 0,
      unite: "U",
    },
    {
      id: 7,
      code: "S6798303",
      name: "Extrémité rétractable BT E4R50-150",
      quantity: 0,
      unite: "U",
    },
    {
      id: 8,
      code: "S6982200",
      name: "Départ monobloc TIPI",
      quantity: 0,
      unite: "U",
    },
    {
      id: 9,
      code: "S6982777",
      name: "Départ monobloc TUR",
      quantity: 0,
      unite: "U",
    },
    {
      id: 10,
      code: "S6943009",
      name: "Fusible 200A-115MM",
      quantity: 0,
      unite: "U",
    },
    {
      id: 11,
      code: "S6943013",
      name: "Fusible 250A-115MM",
      quantity: 0,
      unite: "U",
    },
    {
      id: 12,
      code: "S6943016",
      name: "Fusible 400A-115MM",
      quantity: 0,
      unite: "U",
    },
    {
      id: 13,
      code: "S6943424",
      name: "Fusible 400A-160MM",
      quantity: 0,
      unite: "U",
    },
    {
      id: 14,
      code: "S6943413",
      name: "Fusible 200A-160MM",
      quantity: 0,
      unite: "U",
    },
];

const ADAPTATION_PIED_COLONNE = [
    {
      id: 1,
      code: "S6902433",
      name: "Kit 4 liaisons simples 200 A DIST. 400 A MICHAUD",
      quantity: 0,
      unite: "U",
    },
    {
      id: 2,
      code: "S6902443",
      name: "Kit 4 liaisons simples 200 A DIST. 400 A DEPAGNE",
      quantity: 0,
      unite: "U",
    },
    {
      id: 3,
      code: "S6902473",
      name: "Kit 4 liaisons simples 200 A DIST. 400 A MAEC",
      quantity: 0,
      unite: "U",
    },
    {
      id: 4,
      code: "S6902483",
      name: "Kit 4 liaisons simples 200 A DIST. 400 A SEIFEL",
      quantity: 0,
      unite: "U",
    },
    {
      id: 5,
      code: "S6902434",
      name: "Kit 4 liaisons doubles 200 A DIST. 400 A MICHAUD",
      quantity: 0,
      unite: "U",
    },
    {
      id: 6,
      code: "S6902444",
      name: "Kit 4 liaisons doubles 200 A DIST. 400 A DEPAGNE",
      quantity: 0,
      unite: "U",
    },
    {
      id: 7,
      code: "S6902474",
      name: "Kit 4 liaisons doubles 200 A DIST. 400 A MAEC",
      quantity: 0,
      unite: "U",
    },
    {
      id: 8,
      code: "S6902484",
      name: "Kit 4 liaisons doubles 200 A DIST. 400 A SEIFEL",
      quantity: 0,
      unite: "U",
    },
    {
      id: 9,
      code: "S6902429",
      name: "Distributeur d'arrivée 200A",
      quantity: 0,
      unite: "U",
    },
    {
      id: 10,
      code: "S6902428",
      name: "Distributeur de niveau 200A",
      quantity: 0,
      unite: "U",
    },
    {
      id: 11,
      code: "S6902432",
      name: "Distributeur d'arrivée 400A MICHAUD",
      quantity: 0,
      unite: "U",
    },
    {
      id: 12,
      code: "S6902472",
      name: "Distributeur d'arrivée 400A MAEC",
      quantity: 0,
      unite: "U",
    },
    {
      id: 13,
      code: "S6902482",
      name: "Distributeur d'arrivée 400A SEIFEL",
      quantity: 0,
      unite: "U",
    },
    {
      id: 14,
      code: "S6902442",
      name: "Distributeur d'arrivée 400A DEPAGNE",
      quantity: 0,
      unite: "U",
    },
    {
      id: 15,
      code: "S6902431",
      name: "Distributeur de niveau 400A MICHAUD",
      quantity: 0,
      unite: "U",
    },
    {
      id: 16,
      code: "S6902471",
      name: "Distributeur de niveau 400A MAEC",
      quantity: 0,
      unite: "U",
    },
    {
      id: 17,
      code: "S6902481",
      name: "Distributeur de niveau 400A SEIFEL",
      quantity: 0,
      unite: "U",
    },
    {
      id: 18,
      code: "S6902441",
      name: "Distributeur 400A NIVEAU DEPAGNE",
      quantity: 0,
      unite: "U",
    },
];

const CONSTRUCTION_OUVRAGE_COLLECTIF = [
    {
      id: 1,
      code: "S6902650",
      name: "SPCM protection maximales 200A",
      quantity: 0,
      unite: "U",
    },
    {
      id: 2,
      code: "S6902651",
      name: "SPCM protection 200A avec 2 dérivations 95MM²",
      quantity: 0,
      unite: "U",
    },
    {
      id: 3,
      code: "S6902653",
      name: "SPCM 400A - 2 dérivations. 95MM² 200A",
      quantity: 0,
      unite: "U",
    },
    {
      id: 4,
      code: "S6943405",
      name: "Fusible 100A T0",
      quantity: 0,
      unite: "U",
    },
    {
      id: 5,
      code: "S6941272",
      name: "Adaptateur T2 115MM T00",
      quantity: 0,
      unite: "U",
    },
    {
      id: 6,
      code: "S6943007",
      name: "Fusible 125A T2 115MM",
      quantity: 0,
      unite: "U",
    },
    {
      id: 7,
      code: "S6943009b",
      name: "Fusible 200A T2 115 MM",
      quantity: 0,
      unite: "U",
    },
    {
      id: 8,
      code: "S6943013b",
      name: "Fusible 250A T2 115 MM",
      quantity: 0,
      unite: "U",
    },
    {
      id: 9,
      code: "S6943450",
      name: "Barrette SECT T2 115 MM CU Argent",
      quantity: 0,
      unite: "U",
    },
    {
      id: 10,
      code: "S_kit dériv",
      name: "Kit dérivation",
      quantity: 0,
      unite: "U",
    },
];

const TRAVEE = [
    {
      id: 1,
      code: "S6902664",
      name: "Kit d’extrémité câble 4x35-70 mm²",
      quantity: 0,
      unite: "U",
    },
    {
      id: 2,
      code: "S6902665",
      name: "Kit d’extrémité câble E 4x50-150 mm²",
      quantity: 0,
      unite: "U",
    },
    {
      id: 3,
      code: "S6902661",
      name: "Ensemble triphasé connecteurs 35-70P/16-35D",
      quantity: 0,
      unite: "U",
    },
    {
      id: 4,
      code: "S6902663",
      name: "Ensemble triphasé connecteurs 50-150 P/16-35D",
      quantity: 0,
      unite: "U",
    },
    {
      id: 5,
      code: "S6902662",
      name: "Ensemble monophasé connecteurs 50-150 P/16-35D",
      quantity: 0,
      unite: "U",
    },
    {
      id: 6,
      code: "S6902660",
      name: "Ensemble monophasé connecteurs 35-70 P/16-35D",
      quantity: 0,
      unite: "U",
    },
    {
      id: 7,
      code: "S6902666",
      name: "Coffret d’exploitation câbles IRVE",
      quantity: 0,
      unite: "U",
    },
    {
      id: 8,
      code: "S6918371",
      name: "Fourreau DI coffret exploit ICTA 110, couronne de 25m",
      quantity: 0,
      unite: "M",
    },
    {
      id: 9,
      code: "S6918372",
      name: "Fourreau DI coffret exploit ICTA 110, couronne de 50m",
      quantity: 0,
      unite: "M",
    },
];

const DI = [
    {
      id: 1,
      code: "S6902662",
      name: "Ensemble monophasé connecteurs 50-150P/16-35D",
      quantity: 0,
      unite: "U",
    },
    {
      id: 2,
      code: "S6902660",
      name: "Ensemble monophasé connecteurs 35-70P/16-35D",
      quantity: 0,
      unite: "U",
    },
    {
      id: 3,
      code: "S6902663",
      name: "Ensemble triphasé connecteurs 50-150P/16-35D",
      quantity: 0,
      unite: "U",
    },
    {
      id: 4,
      code: "S6902661",
      name: "Ensemble triphasé connecteurs 35-70P/16-35D",
      quantity: 0,
      unite: "U",
    },
    {
      id: 5,
      code: "S6125736",
      name: "Cable BT IRVE 4*25 CCA(C50m) → livré 200m",
      quantity: 0,
      unite: "U",
    },
    {
      id: 6,
      code: "S6125724",
      name: "Cable N AR BT 2*25 IRVE CCA NF 32-323 cable (MONO) (C100m) → livré 400m",
      quantity: 0,
      unite: "M",
    },
    {
      id: 7,
      code: "S6981222",
      name: "Panneau TRI 25x80 avec CC60A (panneau TRI)",
      quantity: 0,
      unite: "U",
    },
    {
      id: 8,
      code: "S6981210",
      name: "Panneau MONO 25x50 avec CC60A (panneau MONO)",
      quantity: 0,
      unite: "U",
    },
    {
      id: 9,
      code: "S6981155",
      name: "Panneau de contrôle mono sans CC",
      quantity: 0,
      unite: "U",
    },
    {
      id: 10,
      code: "S6981220",
      name: "Panneau de contrôle tri sans CC",
      quantity: 0,
      unite: "U",
    },
    {
      id: 11,
      code: "S6981221",
      name: "Panneau de contrôle tri sans CC",
      quantity: 0,
      unite: "U",
    },
    {
      id: 12,
      code: "S6943514",
      name: "Cartouche à fusible à couteaux tailles 00 CALIBRE AD 45A",
      quantity: 0,
      unite: "U",
    },
    {
      id: 13,
      code: "S6943513",
      name: "Cartouche à fusible à couteaux-00-TYP60A AD (cartouche)",
      quantity: 0,
      unite: "U",
    },
    {
      id: 14,
      code: "S6943512",
      name: "Couteau de neutre taille 00",
      quantity: 0,
      unite: "U",
    },
    {
      id: 15,
      code: "S6930067",
      name: "Disjoncteur Différentiel sélectif 440V T 30A60A (disjoncteur TRI)",
      quantity: 0,
      unite: "U",
    },
    {
      id: 16,
      code: "S6930061",
      name: "Disjoncteur Différentiel sélectif 250 V B 15A45A (disjoncteur MONO)",
      quantity: 0,
      unite: "U",
    },
    { id: 17, code: "S6940036", name: "C/C mono", quantity: 0, unite: "U" },
    { id: 18, code: "S6940038", name: "C/C tri", quantity: 0, unite: "U" },
    {
      id: 19,
      code: "S4074058",
      name: "Compteur LINKY TRI CPL G3-P1-60A",
      quantity: 0,
      unite: "U",
    },
    {
      id: 20,
      code: "S4074060",
      name: "Compteur LINKY MONO CPL G3-P2-60A- AB",
      quantity: 0,
      unite: "U",
    },
    {
      id: 21,
      code: "S4074061",
      name: "Compteur LINKY MONO G1-90A",
      quantity: 0,
      unite: "U",
    },
    {
      id: 22,
      code: "S4074054",
      name: "Compteur LINKY MONO G3-P1-90A",
      quantity: 0,
      unite: "U",
    },
    {
      id: 23,
      code: "S4074062",
      name: "Compteur LINKY TRI G1",
      quantity: 0,
      unite: "U",
    },
];

const CABLES = [
    {
      id: 1,
      code: "S6148440",
      name: "Câble BTS 3X240+115M (ou 120 M) -T",
      quantity: 0,
      unite: "M",
    },
    {
      id: 2,
      code: "S6148435",
      name: "Câble BTS 3X150+95M",
      quantity: 0,
      unite: "M",
    },
    {
      id: 3,
      code: "S6148430",
      name: "Câble BTS 3X95+70M -T",
      quantity: 0,
      unite: "M",
    },
    {
      id: 4,
      code: "S6148430b",
      name: "Câble BTS 3X70+50 M -T",
      quantity: 0,
      unite: "M",
    },
    {
      id: 5,
      code: "S6148167",
      name: "Câble BTS 4X50 -T",
      quantity: 0,
      unite: "M",
    },
    {
      id: 6,
      code: "S6125735",
      name: "Câble BT IRVE 3x240+95 Cca (T250m)",
      quantity: 0,
      unite: "M",
    },
    {
      id: 7,
      code: "S6125733",
      name: "Câble BT IRVE 3x150+70 Cca",
      quantity: 0,
      unite: "M",
    },
    {
      id: 8,
      code: "S6125731",
      name: "Câble BT IRVE 3x95+50 Cca (T250m)",
      quantity: 0,
      unite: "M",
    },
    {
      id: 9,
      code: "S6125730",
      name: "Câble BT IRVE 3x70+50 Cca (T250m)",
      quantity: 0,
      unite: "M",
    },
    {
      id: 10,
      code: "S6125729",
      name: "Câble BT IRVE 4x50+50 Cca (T250m)",
      quantity: 0,
      unite: "M",
    },
    {
      id: 11,
      code: "S6125728",
      name: "Câble BT IRVE 4x50 Cca (C225m)",
      quantity: 0,
      unite: "M",
    },
    {
      id: 12,
      code: "",
      name: "Câble BT 3x240+95 R2V (T250m)",
      quantity: 0,
      unite: "M",
    },
    {
      id: 13,
      code: "",
      name: "Câble BT 3x150+70 R2V",
      quantity: 0,
      unite: "M",
    },
    { id: 14, code: "", name: "Câble BT 3x95+50 R2V", quantity: 0, unite: "M" },
    { id: 15, code: "", name: "Câble BT 3x70+50 R2V", quantity: 0, unite: "M" },
    {
      id: 16,
      code: "S6023909",
      name: "Câble BT U1000 4x50 R2V",
      quantity: 0,
      unite: "M",
    },
    {
      id: 17,
      code: "",
      name: "Câble BT 3x240+95 AR2V (T250m)",
      quantity: 0,
      unite: "M",
    },
    {
      id: 18,
      code: "",
      name: "Câble BT 3x150+70 AR2V",
      quantity: 0,
      unite: "M",
    },
    {
      id: 19,
      code: "",
      name: "Câble BT 3x95+50 AR2V",
      quantity: 0,
      unite: "M",
    },
    {
      id: 20,
      code: "",
      name: "Câble BT 3x70+50 AR2V",
      quantity: 0,
      unite: "M",
    },
    {
      id: 21,
      code: "",
      name: "Câble BT 3x50+50 AR2V",
      quantity: 0,
      unite: "M",
    },
    {
      id: 22,
      code: "",
      name: "Longueur sous collier créé",
      quantity: 0,
      unite: "M",
    },
    {
      id: 23,
      code: "",
      name: "Longueur sous goulotte créé",
      quantity: 0,
      unite: "M",
    },
    {
      id: 24,
      code: "",
      name: "Longueur sous fourreau (enterré) créé",
      quantity: 0,
      unite: "M",
    },
    {
      id: 25,
      code: "",
      name: "Longueur chemin de câble perforé créé",
      quantity: 0,
      unite: "M",
    },
    {
      id: 26,
      code: "",
      name: "Longueur chemin de câble non perforé créé",
      quantity: 0,
      unite: "M",
    },
    {
      id: 27,
      code: "S6910187",
      name: "Chemin de Câbles synthétiques pour parking intérieurs : 150mm",
      quantity: 0,
      unite: "M",
    },
    {
      id: 28,
      code: "S6910188",
      name: "Chemin de Câbles synthétiques pour parking intérieurs : 200mm",
      quantity: 0,
      unite: "M",
    },
    {
      id: 29,
      code: "S6910189",
      name: "Chemin de Câbles synthétiques pour parking intérieurs : 300mm",
      quantity: 0,
      unite: "M",
    },
    { id: 30, code: "S6910190", name: "Pendants", quantity: 0, unite: "U" },
    {
      id: 31,
      code: "S6910191",
      name: "Equerres ou supports",
      quantity: 0,
      unite: "U",
    },
    {
      id: 32,
      code: "S6827764",
      name: "Colliers BIP 180 CV",
      quantity: 0,
      unite: "U",
    },
    {
      id: 33,
      code: "S6827794",
      name: "Colliers BIP 260 CV",
      quantity: 0,
      unite: "U",
    },
];

const TRAVAUX_ANNEXES = [
    {
      id: 1,
      code: "",
      name: "Câble de terre isolé C15-100 (longueur totale)",
      quantity: 0,
      unite: "M",
    },
    {
      id: 2,
      code: "S6902675",
      name: "Placard technique 1 module (armoire SPCM/IS)",
      quantity: 0,
      unite: "U",
    },
    {
      id: 3,
      code: "S6902676",
      name: "Placard technique 3 modules (armoire SPCM/IS)",
      quantity: 0,
      unite: "U",
    },
    {
      id: 4,
      code: "S6902677",
      name: "Placard technique 5 modules (armoire SPCM/IS)",
      quantity: 0,
      unite: "U",
    },
];

const EXTENSION_RESEAU = [
    { id: 1, code: "", name: "BTS - 95 mm²", quantity: 0, unite: "M" },
];

const RACCORDEMENT = [
    { id: 1, code: "S6902033", name: "Borne ECP 3D", quantity: 0, unite: "U" },
    {
      id: 2,
      code: "S6902019",
      name: "Coffret ECP 3D",
      quantity: 0,
      unite: "U",
    },
    { id: 3, code: "S6902053", name: "Borne ECP 2D", quantity: 0, unite: "U" },
    {
      id: 4,
      code: "S6902054",
      name: "Coffret ECP 2D",
      quantity: 0,
      unite: "U",
    },
    {
      id: 5,
      code: "S6902035",
      name: "Kit passage de 2D en 3D",
      quantity: 0,
      unite: "U",
    },
];

const DERIVATION_COLLECTIVE = [
    {
      id: 1,
      code: "S6148430",
      name: "Câble BTS 3X95+70M (50E) touret",
      quantity: 0,
      unite: "M",
    },
    {
      id: 2,
      code: "S6148435",
      name: "Câble BTS 3X150+95M (70E)",
      quantity: 0,
      unite: "M",
    },
    {
      id: 3,
      code: "S6148440",
      name: "Câble BTS 3X240+115M (95E)",
      quantity: 0,
      unite: "M",
    },
    {
      id: 4,
      code: "S6126112",
      name: "Câble non armé BT alu TORS 3X70+54,6",
      quantity: 0,
      unite: "M",
    },
    {
      id: 5,
      code: "S6126260",
      name: "Câble non armé BT alu TORS 3X150+70",
      quantity: 0,
      unite: "M",
    },
];

const DERIVATION_COLLECTIVE_EXTERIEUR = [
    {
      id: 1,
      code: "S6772101",
      name: "Borne REMBT Harmoniée 300 + JDB",
      quantity: 0,
      unite: "U",
    },
    {
      id: 2,
      code: "S6772130",
      name: "Borne REMBT Harmoniée 450 + JDB + RRCP",
      quantity: 0,
      unite: "U",
    },
    {
      id: 3,
      code: "S6772138",
      name: "Borne REMBT Harmoniée 600 + JDB + RRCP",
      quantity: 0,
      unite: "U",
    },
    {
      id: 4,
      code: "S6148162",
      name: "CA C33210 BT AL 4X35 CIR MA - S6148162",
      quantity: 0,
      unite: "M",
    },
    {
      id: 5,
      code: "S6126112",
      name: "Câble non armé BT alu torsadé 3X70+54,6",
      quantity: 0,
      unite: "M",
    },
    {
      id: 6,
      code: "S6792059",
      name: "Ensemble BT NJAS 150-70/240S-95",
      quantity: 0,
      unite: "U",
    },
    {
      id: 7,
      code: "S6729408",
      name: "Capuchon rétractable réseau CRR 16-70 pour du 70²",
      quantity: 0,
      unite: "U",
    },
    {
      id: 8,
      code: "S6729410",
      name: "Capuchon rétractable réseau CRR 150 pourdu 150²",
      quantity: 0,
      unite: "U",
    },
];

const DI_COFFRET_EXPLOITATION = [
    {
      id: 1,
      code: "S6902666",
      name: "Coffret d’exploitation câbles IRVE",
      quantity: 0,
      unite: "U",
    },
    {
      id: 2,
      code: "S6902663",
      name: "Ensemble triphasé connecteurs 50-150 P/16-35D",
      quantity: 0,
      unite: "U",
    },
    {
      id: 3,
      code: "S6125117",
      name: "Câble alu torsadé R SPO 4X25 Couronne 80 m",
      quantity: 0,
      unite: "M",
    },
]

const TRAVAUX_ANNEXES_EXT = [
    {
      id: 1,
      code: "S_cable_terre1",
      name: "Câble alu isolé vert/jaune",
      quantity: 0,
      unite: "M",
    },
    {
      id: 2,
      code: "S_barette_terre",
      name: "Barrette coupure de terre",
      quantity: 0,
      unite: "U",
    },
];

const DI_BOX_FERME = [
    {
      id: 1,
      code: "S6737640",
      name: "Connecteur CBS/CT 70 - 35/70 - 16/35",
      quantity: 0,
      unite: "U",
    },
    {
      id: 2,
      code: "S6737650",
      name: "Connecteur CBS/CT 70 - 54/150 - 16/35",
      quantity: 0,
      unite: "U",
    },
    {
      id: 3,
      code: "S6125074",
      name: "Câble alu torsadé SS PORT 2X25 couronne 100 M",
      quantity: 0,
      unite: "M",
    },
    {
      id: 4,
      code: "S_CTA3522",
      name: "Fourreau classique ICTA 3522",
      quantity: 0,
      unite: "M",
    },
    {
      id: 5,
      code: "S6910193",
      name: "Socle Mobilier Urbain IRVE",
      quantity: 0,
      unite: "U",
    },
    {
      id: 6,
      code: "Scli_protect",
      name: "Dispositif protection socles",
      quantity: 0,
      unite: "U",
    },
    {
      id: 7,
      code: "S6981155",
      name: "Panneau TB 25X22 GP SH BL 2EBCP-AU",
      quantity: 0,
      unite: "U",
    },
    {
      id: 8,
      code: "S6981210",
      name: "Panneau synthétique blanc CBEM+DB CC25X50",
      quantity: 0,
      unite: "U",
    },
    {
      id: 9,
      code: "S6981220",
      name: "Panneau synthétique 25X55 BL TB+DB",
      quantity: 0,
      unite: "U",
    },
    {
      id: 10,
      code: "S6981221",
      name: "Panneau de contrôle TRI 330x330 Type I",
      quantity: 0,
      unite: "U",
    },
    {
      id: 11,
      code: "S6981222",
      name: "Panneau synthétique 25X80 BL TB+DB 1CC60A",
      quantity: 0,
      unite: "U",
    },
    {
      id: 12,
      code: "S6940036",
      name: "C/C Bipolaire 90A PR cartouche TX AD00",
      quantity: 0,
      unite: "U",
    },
    {
      id: 13,
      code: "S6940038",
      name: "C/C Tétrapolaire 60A PR cartouche CTX AD00",
      quantity: 0,
      unite: "U",
    },
    {
      id: 14,
      code: "S6930061",
      name: "Disjoncteur Différentiel sélectif BIP (15A45A)",
      quantity: 0,
      unite: "U",
    },
    {
      id: 15,
      code: "S6930067",
      name: "Disjoncteur Différentiel sélectif 4440V T 30A60A",
      quantity: 0,
      unite: "U",
    },
    {
      id: 16,
      code: "S6771034",
      name: "Lot 50 dispositif blocage disjoncteur",
      quantity: 0,
      unite: "U",
    },
    {
      id: 17,
      code: "S6771033",
      name: "Lot 50 scellé dispositif blocage disjoncteur",
      quantity: 0,
      unite: "U",
    },
    {
      id: 18,
      code: "S6771035",
      name: "Lot 50 étiquettes blocage disj",
      quantity: 0,
      unite: "U",
    },
    {
      id: 19,
      code: "S4074060",
      name: "Compteur LINKY MONO CPL G3-P2-60A- AB",
      quantity: 0,
      unite: "U",
    },
    {
      id: 20,
      code: "S69435142",
      name: "Cartouche fusible à couteau -00-TYP45A-AD",
      quantity: 0,
      unite: "U",
    },
    {
      id: 21,
      code: "S6943512",
      name: "Couteau de Neutre taille 00",
      quantity: 0,
      unite: "U",
    },
];

const DI_MUR_ETXERIEUR = [
    {
      id: 1,
      code: "S6737640",
      name: "Connecteur CBS/CT 70 - 35/70 - 16/35",
      quantity: 0,
      unite: "U",
    },
    {
      id: 2,
      code: "S6737650",
      name: "Connecteur CBS/CT 70 - 54/150 - 16/35",
      quantity: 0,
      unite: "U",
    },
    {
      id: 3,
      code: "S6125074",
      name: "Câble alu torsadé SS PORT 2X25 COUR 100 M",
      quantity: 0,
      unite: "M",
    },
    {
      id: 4,
      code: "S_CTA3522",
      name: "Fourreau classique ICTA 3522",
      quantity: 0,
      unite: "M",
    },
    {
      id: 5,
      code: "S6910193",
      name: "Socle Mobilier Urbain IRVE",
      quantity: 0,
      unite: "U",
    },
    {
      id: 6,
      code: "Scli_protect",
      name: "Dispositif protection socles",
      quantity: 0,
      unite: "U",
    },
    {
      id: 7,
      code: "S6981155",
      name: "Panneau TB 25X22 GP SH BL 2EBCP-AU",
      quantity: 0,
      unite: "U",
    },
    {
      id: 8,
      code: "C6981210",
      name: "Panneau SYNT BLANC CBEM+DB CC25X50",
      quantity: 0,
      unite: "U",
    },
    {
      id: 9,
      code: "C6981220",
      name: "Panneau SYNT 25X55 BL TB+DB",
      quantity: 0,
      unite: "U",
    },
    {
      id: 10,
      code: "C6981221",
      name: "Panneau de contrôle TRI 330x330 Type I",
      quantity: 0,
      unite: "U",
    },
    {
      id: 11,
      code: "C6981222",
      name: "Panneau SYNT 25X80 BL TB+DB 1CC60A",
      quantity: 0,
      unite: "U",
    },
    {
      id: 12,
      code: "C6940036",
      name: "Coupe Circuit bipolaire 90A PR CARTOUCHE CTX AD00",
      quantity: 0,
      unite: "U",
    },
    {
      id: 13,
      code: "C6940038",
      name: "Coupe Circuit tétrapolaire 60A pour cartouche CTX AD00",
      quantity: 0,
      unite: "U",
    },
    {
      id: 14,
      code: "S6940038",
      name: "Coupe Circuit tétrapolaire 60A pour cartouche CTX AD00",
      quantity: 0,
      unite: "U",
    },
    {
      id: 15,
      code: "S6930061",
      name: "Disjoncteur Différentiel sélectif BIP (15A45A)",
      quantity: 0,
      unite: "U",
    },
    {
      id: 16,
      code: "S6930067",
      name: "Disjoncteur Différentiel sélectif 440V T 30A60A",
      quantity: 0,
      unite: "U",
    },
    {
      id: 17,
      code: "S6771034",
      name: "Lot 50 dispositif blocage disj",
      quantity: 0,
      unite: "U",
    },
    {
      id: 18,
      code: "S6771033",
      name: "Lot 50 scellé dispositif blocage Disj",
      quantity: 0,
      unite: "U",
    },
    {
      id: 19,
      code: "S6771035",
      name: "Lot 50 étiquettes blocage disj",
      quantity: 0,
      unite: "U",
    },
    {
      id: 20,
      code: "S4074061",
      name: "Compteur LINKY MONO-CPL G1-P1-90A",
      quantity: 0,
      unite: "U",
    },
    {
      id: 21,
      code: "S4074060",
      name: "Compteur LINKY MONO CPL G3-P2-60A- AB",
      quantity: 0,
      unite: "U",
    },
    {
      id: 22,
      code: "S4074054",
      name: "Compteur LINKY MONO CPL G3-P1-90A",
      quantity: 0,
      unite: "U",
    },
    {
      id: 23,
      code: "S4074062",
      name: "Compteur LINKY TRI-CPL G1-P1-60A",
      quantity: 0,
      unite: "U",
    },
    {
      id: 24,
      code: "S4074058",
      name: "Compteur LINKY TRI CPL G3-P1-60A",
      quantity: 0,
      unite: "U",
    },
    {
      id: 25,
      code: "S69435143",
      name: "Cartouche fusible à couteaux T-00-TYP45A-AD",
      quantity: 0,
      unite: "U",
    },
    {
      id: 26,
      code: "S69435144",
      name: "Cartouche fusible à couteaux-00-TYP45A-AD",
      quantity: 0,
      unite: "U",
    },
    {
      id: 27,
      code: "S6943512",
      name: "Couteau de Neutre taille 00",
      quantity: 0,
      unite: "U",
    },
];

const DI_PARKING_SOL = [
    {
      id: 1,
      code: "S6125074",
      name: "Câble alu torsadé SS PORT 2X25 COUR 100 M",
      quantity: 0,
      unite: "M",
    },
    {
      id: 2,
      code: "S_CTA3522",
      name: "Fourreau classique ICTA3522",
      quantity: 0,
      unite: "M",
    },
    {
      id: 3,
      code: "S6910193",
      name: "Socle Mobilier Urbain IRVE",
      quantity: 0,
      unite: "U",
    },
    {
      id: 4,
      code: "Scli_protect",
      name: "Dispositif protection socles",
      quantity: 0,
      unite: "U",
    },
    {
      id: 5,
      code: "S_mobilier",
      name: "Mobilier extérieur",
      quantity: 0,
      unite: "U",
    },
    {
      id: 6,
      code: "S6980866",
      name: "Coffret Haut CIBE NU COMPLET",
      quantity: 0,
      unite: "U",
    },
    {
      id: 7,
      code: "S6980818",
      name: "Grille de repiquage CIBE 3x35²",
      quantity: 0,
      unite: "U",
    },
    {
      id: 8,
      code: "C6981155",
      name: "Panneau TB 25X22 GP SH BL 2EBCP-AU",
      quantity: 0,
      unite: "U",
    },
    {
      id: 9,
      code: "C6981210",
      name: "Panneau synthétique blanc CBEM+DB CC25X50",
      quantity: 0,
      unite: "U",
    },
    {
      id: 10,
      code: "S6930067",
      name: "Disjoncteur Différentiel sélectif 440V T 30A60A",
      quantity: 0,
      unite: "U",
    },
    {
      id: 11,
      code: "S6771034",
      name: "Lot 50 dispositif blocage disj",
      quantity: 0,
      unite: "U",
    },
    {
      id: 12,
      code: "S6771033",
      name: "Lot 50 scellé dispositif blocage Disj",
      quantity: 0,
      unite: "U",
    },
    {
      id: 13,
      code: "S6771035",
      name: "Lot 50 étiquettes blocage disj",
      quantity: 0,
      unite: "U",
    },
    {
      id: 14,
      code: "S4074061",
      name: "Compteur LINKY MONO-CPL G1-P1-90A",
      quantity: 0,
      unite: "U",
    },
    {
      id: 15,
      code: "S4074060",
      name: "Compteur LINKY MONO CPL G3-P2-60A- AB",
      quantity: 0,
      unite: "U",
    },
    {
      id: 16,
      code: "S4074054",
      name: "Compteur LINKY MONO CPL G3-P1-80A",
      quantity: 0,
      unite: "U",
    },
    {
      id: 17,
      code: "S69435145",
      name: "Cartouche à fusible à couteaux -00-TYP45A-AD",
      quantity: 0,
      unite: "U",
    },
    {
      id: 18,
      code: "S6943512",
      name: "Couteau de Neutre taille 00",
      quantity: 0,
      unite: "U",
    },
];

export {
    RACCORDEMENT_RESEAU,
    ADAPTATION_PIED_COLONNE,
    CONSTRUCTION_OUVRAGE_COLLECTIF,
    TRAVEE,
    DI,
    CABLES,
    TRAVAUX_ANNEXES,
    EXTENSION_RESEAU,
    RACCORDEMENT,
    DERIVATION_COLLECTIVE,
    DERIVATION_COLLECTIVE_EXTERIEUR,
    DI_COFFRET_EXPLOITATION,
    TRAVAUX_ANNEXES_EXT,
    DI_BOX_FERME,
    DI_MUR_ETXERIEUR, // 👈 matches your current name (with ETXERIEUR)
    DI_PARKING_SOL,
  };